CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti VARCHAR(120) NOT NULL,
    token_hash VARCHAR(120) NOT NULL,
    user_uuid UUID NOT NULL,
    role VARCHAR(30) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    rotated_at TIMESTAMP NULL,

    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_token_hash ON refresh_tokens(token_hash);
CREATE INDEX idx_refresh_tokens_user_uuid ON refresh_tokens(user_uuid);
