# --- Cache Caffeine: users (D-13) ---
quarkus:
  cache:
    caffeine:
      users:
        initial-capacity: 10
        maximum-size: 100
        expire-after-write: 60s
      clientes:
        initial-capacity: 10
        maximum-size: 100
        expire-after-write: 60s
      pecas:
        initial-capacity: 20
        maximum-size: 200
        expire-after-write: 60s
      requisicoes:
        initial-capacity: 20
        maximum-size: 200
        expire-after-write: 60s
      nf_entradas:
        initial-capacity: 20
        maximum-size: 200
        expire-after-write: 60s
