apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: mekano
  namespace: mekano-system

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:
          - path: /($)(.*)
            pathType: ImplementationSpecific

            backend:
              service:
                name: mekano
                port:
                  number: 8080

          - path: /evolution(/|$)(.*)
            pathType: ImplementationSpecific

            backend:
              service:
                name: evolution-api
                port:
                  number: 5033
