-- V10__create_requisicoes_compra_table.sql
-- Migration: cria tabela requisicoes_compra para RequisicaoCompraEntity

CREATE TABLE requisicoes_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    peca_id UUID NOT NULL,
    quantidade INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    motivo VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    deleted_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_requisicoes_compra_uuid ON requisicoes_compra(uuid);
CREATE INDEX idx_requisicoes_compra_peca_id ON requisicoes_compra(peca_id);
CREATE INDEX idx_requisicoes_compra_is_active ON requisicoes_compra(is_active);
