-- V11__create_nf_entradas_table.sql
-- Migration: cria tabela nf_entradas para NfEntradaEntity

CREATE TABLE nf_entradas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    chave_acesso VARCHAR(44) NOT NULL,
    valor_total DECIMAL(12,2) NOT NULL,
    peca_id UUID NOT NULL,
    requisicao_compra_id UUID NOT NULL,
    data_recebimento TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    deleted_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_nf_entradas_uuid ON nf_entradas(uuid);
CREATE INDEX idx_nf_entradas_peca_id ON nf_entradas(peca_id);
CREATE INDEX idx_nf_entradas_req_compra_id ON nf_entradas(requisicao_compra_id);
CREATE INDEX idx_nf_entradas_chave_acesso ON nf_entradas(chave_acesso);
CREATE INDEX idx_nf_entradas_is_active ON nf_entradas(is_active);
