-- V7__create_ordens_de_servico_tables.sql
-- Migration: criação das tabelas de Ordem de Serviço (Issue #19)
-- 3 tabelas: ordens_de_servico (aggregate root), servicos_executados, pecas_usadas
-- H2 compatible: BIGINT GENERATED BY DEFAULT AS IDENTITY, sem BIGSERIAL

CREATE TABLE ordens_de_servico (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid                  UUID         NOT NULL,
    cliente_id            UUID         NOT NULL,
    veiculo_id            UUID         NOT NULL,
    descricao_problema    VARCHAR(1000) NOT NULL,
    status                VARCHAR(30)  NOT NULL DEFAULT 'RECEBIDA',
    motivo_cancelamento   VARCHAR(500),
    version               BIGINT       NOT NULL DEFAULT 0,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP,
    created_by            UUID,
    updated_by            UUID,
    deleted_at            TIMESTAMP,
    is_active             BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_ordens_de_servico PRIMARY KEY (id),
    CONSTRAINT uq_ordens_de_servico_uuid UNIQUE (uuid)
);

CREATE INDEX idx_os_status ON ordens_de_servico (status);
CREATE INDEX idx_os_cliente_id ON ordens_de_servico (cliente_id);
CREATE INDEX idx_os_is_active ON ordens_de_servico (is_active);

CREATE TABLE servicos_executados (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid        UUID         NOT NULL,
    os_id       BIGINT       NOT NULL,
    servico_id  UUID         NOT NULL,
    valor       DECIMAL(10,2) NOT NULL,
    observacao  VARCHAR(500),
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT pk_servicos_executados PRIMARY KEY (id),
    CONSTRAINT uq_servicos_executados_uuid UNIQUE (uuid),
    CONSTRAINT fk_se_os FOREIGN KEY (os_id) REFERENCES ordens_de_servico(id)
);

CREATE TABLE pecas_usadas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid        UUID         NOT NULL,
    os_id       BIGINT       NOT NULL,
    peca_id     UUID         NOT NULL,
    quantidade  INT          NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT pk_pecas_usadas PRIMARY KEY (id),
    CONSTRAINT uq_pecas_usadas_uuid UNIQUE (uuid),
    CONSTRAINT fk_pu_os FOREIGN KEY (os_id) REFERENCES ordens_de_servico(id)
);
