-- V12__create_ordens_de_servico_tables.sql
-- Migration original: criação das tabelas de Ordem de Serviço (Issue #19)
-- ⚠ SUPERSEDED by V18 (executada com out-of-order, V12 roda DEPOIS de V18)
-- Mantida para preservar histórico.
-- H2-POSTGRESQL COMPATIBLE: usa DO $$ com EXECUTE para compatibilidade H2

-- NOTA: ordens_de_servico é criada por V18 (schema completo).
-- V12 NÃO cria ordens_de_servico para evitar conflito de colunas
-- (V12: cliente_id; V18: cliente_uuid) quando V12 roda antes via outOfOrder.

-- NOTA: servicos_executados / pecas_usadas são tabelas do design original
-- que não possuem JPA entities correspondentes no código atual (substituídas
-- por V18+). Mantidas apenas para preservar histórico de migration.
-- As FK constraints foram omitidas porque ordens_de_servico ainda não existe
-- quando V12 roda (out-of-order antes de V18).

CREATE TABLE IF NOT EXISTS servicos_executados (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid        UUID         NOT NULL,
    os_id       BIGINT       NOT NULL,
    servico_id  UUID         NOT NULL,
    valor       DECIMAL(10,2) NOT NULL,
    observacao  VARCHAR(500),
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT pk_servicos_executados PRIMARY KEY (id),
    CONSTRAINT uq_servicos_executados_uuid UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS pecas_usadas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid        UUID         NOT NULL,
    os_id       BIGINT       NOT NULL,
    peca_id     UUID         NOT NULL,
    quantidade  INT          NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT pk_pecas_usadas PRIMARY KEY (id),
    CONSTRAINT uq_pecas_usadas_uuid UNIQUE (uuid)
);
