CREATE TABLE user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL,
    user_uuid UUID NOT NULL,
    role VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by UUID NOT NULL,
    CONSTRAINT uk_user_roles_uuid UNIQUE (uuid),
    CONSTRAINT uk_user_roles_user_role UNIQUE (user_uuid, role)
);

CREATE INDEX idx_user_roles_user_uuid ON user_roles(user_uuid);
CREATE INDEX idx_user_roles_role ON user_roles(role);