ALTER TABLE user_roles
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE user_roles
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE user_roles
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_roles
    ADD COLUMN IF NOT EXISTS created_by UUID;

ALTER TABLE user_roles
    ADD COLUMN IF NOT EXISTS updated_by UUID;

ALTER TABLE user_roles
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;