-- V18__create_ordens_de_servico_table.sql
-- Migration: cria tabela ordens_de_servico para OrdemDeServicoEntity

CREATE TABLE IF NOT EXISTS ordens_de_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    cliente_uuid UUID NOT NULL,
    veiculo_uuid UUID NOT NULL,
    descricao_problema VARCHAR(500) NOT NULL,
    status VARCHAR(30) NOT NULL,
    motivo_cancelamento VARCHAR(500),
    orcamento_uuid UUID,
    mecanico_uuid UUID,
    execucao_iniciada_em TIMESTAMP,
    execucao_finalizada_em TIMESTAMP,
    observacao_execucao VARCHAR(1000),
    data_aprovacao TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    deleted_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ordens_servico_uuid ON ordens_de_servico(uuid);
CREATE INDEX IF NOT EXISTS idx_ordens_servico_status ON ordens_de_servico(status);
CREATE INDEX IF NOT EXISTS idx_ordens_servico_cliente ON ordens_de_servico(cliente_uuid);
CREATE INDEX IF NOT EXISTS idx_ordens_servico_is_active ON ordens_de_servico(is_active);
