-- V19__create_orcamentos_table.sql
-- Migration: cria tabela orcamentos para OrcamentoEntity

CREATE TABLE orcamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    descricao VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    valor_total NUMERIC(12, 2) NOT NULL,
    ordem_servico_uuid UUID,
    data_expiracao TIMESTAMP,
    itens_json TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    deleted_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_orcamentos_uuid ON orcamentos(uuid);
CREATE INDEX idx_orcamentos_os_uuid ON orcamentos(ordem_servico_uuid);
CREATE INDEX idx_orcamentos_status ON orcamentos(status);
CREATE INDEX idx_orcamentos_is_active ON orcamentos(is_active);
