-- V25__create_ordens_servico_table.sql
-- Migration: cria tabela ordens_servico para OrdemServicoEntity (feat/25)
-- Adicionada posteriormente à V18 — necessária como migration separada
-- porque V18 já foi aplicada antes desta tabela ser incluída.

CREATE TABLE IF NOT EXISTS ordens_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ordens_servico_simple_uuid ON ordens_servico(uuid);