CREATE TABLE IF NOT EXISTS os_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    os_uuid UUID NOT NULL,
    acao VARCHAR(40) NOT NULL,
    usuario_email VARCHAR(180),
    observacao VARCHAR(1000),
    metadata_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_os_audit_logs_os_uuid
    ON os_audit_logs (os_uuid);

CREATE INDEX IF NOT EXISTS idx_os_audit_logs_os_uuid_created_at
    ON os_audit_logs (os_uuid, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_os_audit_logs_acao
    ON os_audit_logs (acao);