-- V28: Create processed_events table for idempotency control
CREATE TABLE processed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id VARCHAR(255) NOT NULL UNIQUE,
    tipo_evento VARCHAR(100) NOT NULL,
    origem_agregado VARCHAR(50) NOT NULL,
    uuid_agregado UUID NOT NULL,
    payload TEXT NOT NULL,
    processado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_processed_events_uuid ON processed_events(uuid_agregado);
CREATE INDEX idx_processed_events_tipo ON processed_events(tipo_evento);
CREATE INDEX idx_processed_events_evento_id ON processed_events(evento_id);
