-- V35__create_os_itens_table.sql
-- Migration: cria tabela os_itens para itens (peças/serviços) de Ordens de Serviço

CREATE TABLE IF NOT EXISTS os_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    os_uuid UUID NOT NULL,
    referencia_uuid UUID NOT NULL,
    tipo VARCHAR(10) NOT NULL,
    descricao VARCHAR(500),
    quantidade BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    deleted_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_os_itens UNIQUE (os_uuid, referencia_uuid, tipo)
);

CREATE INDEX idx_os_itens_uuid ON os_itens(uuid);
CREATE INDEX idx_os_itens_os_uuid ON os_itens(os_uuid);
CREATE INDEX idx_os_itens_tipo ON os_itens(tipo);
CREATE INDEX idx_os_itens_is_active ON os_itens(is_active);
