-- V36: Suporte a múltiplos itens na Requisição de Compra
-- Cria tabela de itens, migreira dados existentes e remove colunas obsoletas

-- 1. Criar tabela de itens da requisição de compra
CREATE TABLE itens_requisicao_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid UUID NOT NULL UNIQUE,
    requisicao_compra_id UUID NOT NULL,
    peca_id UUID NOT NULL,
    quantidade INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    deleted_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id)
);

CREATE INDEX idx_itens_requisicao_compra_requisicao ON itens_requisicao_compra(requisicao_compra_id);
CREATE INDEX idx_itens_requisicao_compra_peca ON itens_requisicao_compra(peca_id);

-- 2. Migrar dados existentes: cada requisição existente vira um item
INSERT INTO itens_requisicao_compra (uuid, requisicao_compra_id, peca_id, quantidade, created_at, is_active)
SELECT
    gen_random_uuid(),
    uuid,
    peca_id,
    quantidade,
    COALESCE(created_at, CURRENT_TIMESTAMP),
    TRUE
FROM requisicoes_compra
WHERE is_active = TRUE AND peca_id IS NOT NULL;

-- 3. Remover colunas obsoletas de requisicoes_compra
ALTER TABLE requisicoes_compra DROP COLUMN IF EXISTS peca_id;
ALTER TABLE requisicoes_compra DROP COLUMN IF EXISTS quantidade;

-- 4. Remover peca_id de nf_entradas (NF agora cobre todos os itens via requisição)
ALTER TABLE nf_entradas DROP COLUMN IF EXISTS peca_id;
