-- V6__create_servicos_table.sql
-- Migration: criação da tabela servicos (Issue #17)
-- PK sequencial (IDENTITY) + UUID público (padrão Hybrid ID)
-- CHECK constraint para valor > 0
-- Partial unique index no nome (apenas ativos) — compatível com soft delete

CREATE TABLE servicos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid        UUID         NOT NULL,
    nome        VARCHAR(150) NOT NULL,
    descricao   VARCHAR(500),
    valor       DECIMAL(10,2) NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    created_by  UUID,
    updated_by  UUID,
    deleted_at  TIMESTAMP,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_servicos PRIMARY KEY (id),
    CONSTRAINT uq_servicos_uuid UNIQUE (uuid),
    CONSTRAINT chk_servicos_valor CHECK (valor > 0)
);

CREATE INDEX idx_servicos_is_active ON servicos (is_active);

-- Partial unique index: unicidade de nome apenas entre registros ativos
CREATE UNIQUE INDEX uq_servicos_nome_active ON servicos (nome) WHERE is_active = TRUE;