-- V7__create_clientes_table.sql
-- Migration: criacao da tabela clientes
-- Endereco achatado em colunas separadas (D-20)

CREATE TABLE clientes
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid                 UUID         NOT NULL,
    nome                 VARCHAR(255) NOT NULL,
    cpf                  VARCHAR(11)  NOT NULL,
    email                VARCHAR(255) NOT NULL,
    telefone             VARCHAR(11),
    endereco_logradouro  VARCHAR(255),
    endereco_numero      VARCHAR(20),
    endereco_bairro      VARCHAR(255),
    endereco_cidade      VARCHAR(255),
    endereco_uf          VARCHAR(2),
    endereco_cep         VARCHAR(8),
    created_at           TIMESTAMP    NOT NULL,
    updated_at           TIMESTAMP,
    created_by           UUID,
    updated_by           UUID,
    deleted_at           TIMESTAMP,
    is_active            BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_clientes PRIMARY KEY (id),
    CONSTRAINT uq_clientes_uuid UNIQUE (uuid),
    CONSTRAINT uq_clientes_cpf UNIQUE (cpf)
);

CREATE INDEX idx_clientes_is_active ON clientes (is_active);
