-- V9__create_pecas_table.sql
-- Migration: cria tabela pecas para PecaEntity

CREATE TABLE pecas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    descricao VARCHAR(255) NOT NULL,
    saldo INTEGER NOT NULL,
    estoque_minimo INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    deleted_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_pecas_uuid ON pecas(uuid);
CREATE INDEX idx_pecas_is_active ON pecas(is_active);
